package net.sourceforge.xbrz;

import static org.junit.Assert.assertEquals;

import java.awt.image.BufferedImage;
import java.io.IOException;

import javax.imageio.ImageIO;

import org.junit.Test;

import net.sourceforge.xbrz.Xbrz.ScalerCfg;

public abstract class AbstractScalerTest {

    protected abstract Xbrz xbrz();

    @Test
    public void basicShapes() throws Exception {
        testImage("test/basic-shapes");
    }

    @Test
    public void fullPicture() throws Exception {
        // Reference images generated by the original ScalerTest tool
        // appear to differ slightly - likely the YCbCr color distance
        // calculation varies between Java and C++.
        testImage("test/gbamockup", 1.0);
    }

    @Test
    public void someAlpha() throws Exception {
        testImage("test/down-arrow");
    }

    @Test
    public void alphaAtImageBoundary() throws Exception {
        testImage("test/open-folder");
    }

    @Test
    public void colorDistanceRGB() throws Exception {
        // Expected result differences around some edges.
        testImage(new Xbrz(xbrz().scaler.scale(),
                false, new ScalerCfg(), ColorDistance.rgb()), "test/gbamockup", 3.0);
    }

    @Test
    public void colorDistanceYCbCrBuffered() throws Exception {
        // Expected result differences around some edges.
        testImage(new Xbrz(xbrz().scaler.scale(), false,
                new ScalerCfg(), ColorDistance.bufferedYCbCr(5)), "test/gbamockup", 3.0);
    }

    private void testImage(String name) throws IOException {
        testImage(name, 0.001);
    }

    private void testImage(String name, double deviation) throws IOException {
        testImage(xbrz(), name, deviation);
    }

    private void testImage(Xbrz xbrz, String name, double deviation) throws IOException {
        final int factor = xbrz.scaler.scale();

        BufferedImage source = ImageIO.read(AbstractScalerTest.class.getResource(name + ".png"));
        int srcWidth = source.getWidth();
        int srcHeight = source.getHeight();
        int[] srcPixels = new int[srcWidth * srcHeight];
        source.getRGB(0, 0, srcWidth, srcHeight, srcPixels, 0, srcWidth);

        int destWidth = srcWidth * factor;
        int destHeight = srcHeight * factor;
        int[] destPixels = new int[destWidth * destHeight];
        xbrz.scaleImage(srcPixels, destPixels, srcWidth, srcHeight);

        BufferedImage reference = ImageIO.read(AbstractScalerTest.class.getResource(name + "@" + factor + "xbrz.png"));
        int[] refPixels = new int[reference.getWidth() * reference.getHeight()];
        reference.getRGB(0, 0, reference.getWidth(), reference.getHeight(), refPixels, 0, reference.getWidth());
        assertPixels(destPixels, refPixels, deviation);
    }

    private static void assertPixels(int[] destPixels, int[] refPixels, double deviation) {
        assertEquals("pixels size", refPixels.length, destPixels.length);
        int mismatch = 0;
        for (int i = 0, len = refPixels.length; i < len; i++) {
            if (destPixels[i] != refPixels[i]) {
                mismatch += 1;
            }
        }
        double percent = (destPixels.length - mismatch) * 100.0 / destPixels.length;
        System.out.printf("Pixels match: %d (%f%%) of %d%n",
                          destPixels.length - mismatch, percent, destPixels.length);
        assertEquals("pixels", 100.0, percent, deviation);
    }
    
}
